development:
  adapter: postgresql
  encoding: unicode
  database: assessment_development
  pool: 5
  username: bhanu
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: assessment_test
  pool: 5
  username: bhanu
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: assessment_production
  pool: 5
  username: bhanu
  password:
